# coding: utf-8

"""
    Criteo API Transition Swagger

    This is used to help Criteo clients transition from MAPI to Criteo API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AdSetDeliveryLimitations(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'environments': 'list[str]',
        'devices': 'list[str]',
        'operating_systems': 'list[str]'
    }

    attribute_map = {
        'environments': 'environments',
        'devices': 'devices',
        'operating_systems': 'operatingSystems'
    }

    def __init__(self, environments=None, devices=None, operating_systems=None):  # noqa: E501
        """AdSetDeliveryLimitations - a model defined in OpenAPI"""  # noqa: E501

        self._environments = None
        self._devices = None
        self._operating_systems = None
        self.discriminator = None

        if environments is not None:
            self.environments = environments
        if devices is not None:
            self.devices = devices
        if operating_systems is not None:
            self.operating_systems = operating_systems

    @property
    def environments(self):
        """Gets the environments of this AdSetDeliveryLimitations.  # noqa: E501

        List of environments which the ad set should target  # noqa: E501

        :return: The environments of this AdSetDeliveryLimitations.  # noqa: E501
        :rtype: list[str]
        """
        return self._environments

    @environments.setter
    def environments(self, environments):
        """Sets the environments of this AdSetDeliveryLimitations.

        List of environments which the ad set should target  # noqa: E501

        :param environments: The environments of this AdSetDeliveryLimitations.  # noqa: E501
        :type: list[str]
        """

        self._environments = environments

    @property
    def devices(self):
        """Gets the devices of this AdSetDeliveryLimitations.  # noqa: E501

        List of devices which the ad set should target  # noqa: E501

        :return: The devices of this AdSetDeliveryLimitations.  # noqa: E501
        :rtype: list[str]
        """
        return self._devices

    @devices.setter
    def devices(self, devices):
        """Sets the devices of this AdSetDeliveryLimitations.

        List of devices which the ad set should target  # noqa: E501

        :param devices: The devices of this AdSetDeliveryLimitations.  # noqa: E501
        :type: list[str]
        """

        self._devices = devices

    @property
    def operating_systems(self):
        """Gets the operating_systems of this AdSetDeliveryLimitations.  # noqa: E501

        List of operating systems which the ad set should target  # noqa: E501

        :return: The operating_systems of this AdSetDeliveryLimitations.  # noqa: E501
        :rtype: list[str]
        """
        return self._operating_systems

    @operating_systems.setter
    def operating_systems(self, operating_systems):
        """Sets the operating_systems of this AdSetDeliveryLimitations.

        List of operating systems which the ad set should target  # noqa: E501

        :param operating_systems: The operating_systems of this AdSetDeliveryLimitations.  # noqa: E501
        :type: list[str]
        """

        self._operating_systems = operating_systems

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdSetDeliveryLimitations):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
