# coding: utf-8

"""
    Criteo API Transition Swagger

    This is used to help Criteo clients transition from MAPI to Criteo API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class AdSetFrequencyCapping(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'frequency': 'str',
        'maximum_impressions': 'int'
    }

    attribute_map = {
        'frequency': 'frequency',
        'maximum_impressions': 'maximumImpressions'
    }

    def __init__(self, frequency=None, maximum_impressions=None):  # noqa: E501
        """AdSetFrequencyCapping - a model defined in OpenAPI"""  # noqa: E501

        self._frequency = None
        self._maximum_impressions = None
        self.discriminator = None

        if frequency is not None:
            self.frequency = frequency
        if maximum_impressions is not None:
            self.maximum_impressions = maximum_impressions

    @property
    def frequency(self):
        """Gets the frequency of this AdSetFrequencyCapping.  # noqa: E501

        Period on which impression limitation is calculated  # noqa: E501

        :return: The frequency of this AdSetFrequencyCapping.  # noqa: E501
        :rtype: str
        """
        return self._frequency

    @frequency.setter
    def frequency(self, frequency):
        """Sets the frequency of this AdSetFrequencyCapping.

        Period on which impression limitation is calculated  # noqa: E501

        :param frequency: The frequency of this AdSetFrequencyCapping.  # noqa: E501
        :type: str
        """

        self._frequency = frequency

    @property
    def maximum_impressions(self):
        """Gets the maximum_impressions of this AdSetFrequencyCapping.  # noqa: E501

        Maximum impressions for the specified period  # noqa: E501

        :return: The maximum_impressions of this AdSetFrequencyCapping.  # noqa: E501
        :rtype: int
        """
        return self._maximum_impressions

    @maximum_impressions.setter
    def maximum_impressions(self, maximum_impressions):
        """Sets the maximum_impressions of this AdSetFrequencyCapping.

        Maximum impressions for the specified period  # noqa: E501

        :param maximum_impressions: The maximum_impressions of this AdSetFrequencyCapping.  # noqa: E501
        :type: int
        """

        self._maximum_impressions = maximum_impressions

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdSetFrequencyCapping):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
