# coding: utf-8

"""
    Criteo API Transition Swagger

    This is used to help Criteo clients transition from MAPI to Criteo API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class ContactlistOperationAttributes(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'contact_list_id': 'str',
        'operation': 'str',
        'request_date': 'datetime',
        'identifier_type': 'str',
        'nb_valid_identifiers': 'int',
        'nb_invalid_identifiers': 'int',
        'sample_invalid_identifiers': 'list[str]'
    }

    attribute_map = {
        'contact_list_id': 'contactListId',
        'operation': 'operation',
        'request_date': 'requestDate',
        'identifier_type': 'identifierType',
        'nb_valid_identifiers': 'nbValidIdentifiers',
        'nb_invalid_identifiers': 'nbInvalidIdentifiers',
        'sample_invalid_identifiers': 'sampleInvalidIdentifiers'
    }

    def __init__(self, contact_list_id=None, operation=None, request_date=None, identifier_type=None, nb_valid_identifiers=None, nb_invalid_identifiers=None, sample_invalid_identifiers=None):  # noqa: E501
        """ContactlistOperationAttributes - a model defined in OpenAPI"""  # noqa: E501

        self._contact_list_id = None
        self._operation = None
        self._request_date = None
        self._identifier_type = None
        self._nb_valid_identifiers = None
        self._nb_invalid_identifiers = None
        self._sample_invalid_identifiers = None
        self.discriminator = None

        if contact_list_id is not None:
            self.contact_list_id = contact_list_id
        self.operation = operation
        if request_date is not None:
            self.request_date = request_date
        if identifier_type is not None:
            self.identifier_type = identifier_type
        if nb_valid_identifiers is not None:
            self.nb_valid_identifiers = nb_valid_identifiers
        if nb_invalid_identifiers is not None:
            self.nb_invalid_identifiers = nb_invalid_identifiers
        if sample_invalid_identifiers is not None:
            self.sample_invalid_identifiers = sample_invalid_identifiers

    @property
    def contact_list_id(self):
        """Gets the contact_list_id of this ContactlistOperationAttributes.  # noqa: E501

        the affected user list id  # noqa: E501

        :return: The contact_list_id of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: str
        """
        return self._contact_list_id

    @contact_list_id.setter
    def contact_list_id(self, contact_list_id):
        """Sets the contact_list_id of this ContactlistOperationAttributes.

        the affected user list id  # noqa: E501

        :param contact_list_id: The contact_list_id of this ContactlistOperationAttributes.  # noqa: E501
        :type: str
        """

        self._contact_list_id = contact_list_id

    @property
    def operation(self):
        """Gets the operation of this ContactlistOperationAttributes.  # noqa: E501

        The action recorded  # noqa: E501

        :return: The operation of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: str
        """
        return self._operation

    @operation.setter
    def operation(self, operation):
        """Sets the operation of this ContactlistOperationAttributes.

        The action recorded  # noqa: E501

        :param operation: The operation of this ContactlistOperationAttributes.  # noqa: E501
        :type: str
        """
        if operation is None:
            raise ValueError("Invalid value for `operation`, must not be `None`")  # noqa: E501

        self._operation = operation

    @property
    def request_date(self):
        """Gets the request_date of this ContactlistOperationAttributes.  # noqa: E501

        When the action was recorded  # noqa: E501

        :return: The request_date of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: datetime
        """
        return self._request_date

    @request_date.setter
    def request_date(self, request_date):
        """Sets the request_date of this ContactlistOperationAttributes.

        When the action was recorded  # noqa: E501

        :param request_date: The request_date of this ContactlistOperationAttributes.  # noqa: E501
        :type: datetime
        """

        self._request_date = request_date

    @property
    def identifier_type(self):
        """Gets the identifier_type of this ContactlistOperationAttributes.  # noqa: E501

        The schema specified for of the identifiers  # noqa: E501

        :return: The identifier_type of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: str
        """
        return self._identifier_type

    @identifier_type.setter
    def identifier_type(self, identifier_type):
        """Sets the identifier_type of this ContactlistOperationAttributes.

        The schema specified for of the identifiers  # noqa: E501

        :param identifier_type: The identifier_type of this ContactlistOperationAttributes.  # noqa: E501
        :type: str
        """

        self._identifier_type = identifier_type

    @property
    def nb_valid_identifiers(self):
        """Gets the nb_valid_identifiers of this ContactlistOperationAttributes.  # noqa: E501

        How many identifiers were valid for the specified schema  # noqa: E501

        :return: The nb_valid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: int
        """
        return self._nb_valid_identifiers

    @nb_valid_identifiers.setter
    def nb_valid_identifiers(self, nb_valid_identifiers):
        """Sets the nb_valid_identifiers of this ContactlistOperationAttributes.

        How many identifiers were valid for the specified schema  # noqa: E501

        :param nb_valid_identifiers: The nb_valid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :type: int
        """

        self._nb_valid_identifiers = nb_valid_identifiers

    @property
    def nb_invalid_identifiers(self):
        """Gets the nb_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501

        How many identifiers were invalid for the specified schema  # noqa: E501

        :return: The nb_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: int
        """
        return self._nb_invalid_identifiers

    @nb_invalid_identifiers.setter
    def nb_invalid_identifiers(self, nb_invalid_identifiers):
        """Sets the nb_invalid_identifiers of this ContactlistOperationAttributes.

        How many identifiers were invalid for the specified schema  # noqa: E501

        :param nb_invalid_identifiers: The nb_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :type: int
        """

        self._nb_invalid_identifiers = nb_invalid_identifiers

    @property
    def sample_invalid_identifiers(self):
        """Gets the sample_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501

        A sample of invalid identifiers if there is some  # noqa: E501

        :return: The sample_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :rtype: list[str]
        """
        return self._sample_invalid_identifiers

    @sample_invalid_identifiers.setter
    def sample_invalid_identifiers(self, sample_invalid_identifiers):
        """Sets the sample_invalid_identifiers of this ContactlistOperationAttributes.

        A sample of invalid identifiers if there is some  # noqa: E501

        :param sample_invalid_identifiers: The sample_invalid_identifiers of this ContactlistOperationAttributes.  # noqa: E501
        :type: list[str]
        """

        self._sample_invalid_identifiers = sample_invalid_identifiers

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ContactlistOperationAttributes):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
