# coding: utf-8

"""
    Criteo API Transition Swagger

    This is used to help Criteo clients transition from MAPI to Criteo API  # noqa: E501

    The version of the OpenAPI document: 1.0
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six


class CriteoApiDataOfPortfolioMessage(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'type': 'str',
        'id': 'str',
        'attributes': 'PortfolioMessage',
        'meta': 'object'
    }

    attribute_map = {
        'type': 'type',
        'id': 'id',
        'attributes': 'attributes',
        'meta': 'meta'
    }

    def __init__(self, type=None, id=None, attributes=None, meta=None):  # noqa: E501
        """CriteoApiDataOfPortfolioMessage - a model defined in OpenAPI"""  # noqa: E501

        self._type = None
        self._id = None
        self._attributes = None
        self._meta = None
        self.discriminator = None

        if type is not None:
            self.type = type
        if id is not None:
            self.id = id
        if attributes is not None:
            self.attributes = attributes
        if meta is not None:
            self.meta = meta

    @property
    def type(self):
        """Gets the type of this CriteoApiDataOfPortfolioMessage.  # noqa: E501

        A string containing the entity type  # noqa: E501

        :return: The type of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this CriteoApiDataOfPortfolioMessage.

        A string containing the entity type  # noqa: E501

        :param type: The type of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def id(self):
        """Gets the id of this CriteoApiDataOfPortfolioMessage.  # noqa: E501

        A opaque string containing the unique Id of the entity  # noqa: E501

        :return: The id of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CriteoApiDataOfPortfolioMessage.

        A opaque string containing the unique Id of the entity  # noqa: E501

        :param id: The id of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def attributes(self):
        """Gets the attributes of this CriteoApiDataOfPortfolioMessage.  # noqa: E501


        :return: The attributes of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :rtype: PortfolioMessage
        """
        return self._attributes

    @attributes.setter
    def attributes(self, attributes):
        """Sets the attributes of this CriteoApiDataOfPortfolioMessage.


        :param attributes: The attributes of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :type: PortfolioMessage
        """

        self._attributes = attributes

    @property
    def meta(self):
        """Gets the meta of this CriteoApiDataOfPortfolioMessage.  # noqa: E501

        A meta object that contains application-specific metadata  # noqa: E501

        :return: The meta of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :rtype: object
        """
        return self._meta

    @meta.setter
    def meta(self, meta):
        """Sets the meta of this CriteoApiDataOfPortfolioMessage.

        A meta object that contains application-specific metadata  # noqa: E501

        :param meta: The meta of this CriteoApiDataOfPortfolioMessage.  # noqa: E501
        :type: object
        """

        self._meta = meta

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CriteoApiDataOfPortfolioMessage):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
